# Generated by Django 5.2.17 on 2026-10-01 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_check_in_date_booking_check_out_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='passengers',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
